# Use this workspace to collaborate
workspace:
  id: 8e28f626-bc3e-4157-811e-a86b1e4b737d

# All resources in the `postman/` folder are automatically registered in Local View.
# Point to additional files outside the `postman/` folder to register them individually. Example:
#localResources:
#  collections:
#    - ../tests/E2E Test Collection/
